name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.55.1
          working_directory: ${{ github.workspace }}

      - name: Install Rust toolchain
        run: rustup default stable

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose
